# ===================================
#  Rest Behavior Config
# ===================================

# Allowed Rest Actions
allowedActions:
  store:

# Model Class name
modelClass: Mohsin\Mobile\Models\Install
