# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: mohsin.mobile::lang.install.label

# Model Form Field configuration
form: $/mohsin/mobile/models/install/fields.yaml

# Model Class name
modelClass: Mohsin\Mobile\Models\Install

# Default redirect location
defaultRedirect: mohsin/mobile/installs
