# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Platform

# Model Form Field configuration
form: $/mohsin/mobile/models/platform/fields.yaml

# Model Class name
modelClass: Mohsin\Mobile\Models\Platform

# Default redirect location
defaultRedirect: mohsin/mobile/platforms

# Create page
create:
    title: Create Platform
    redirect: mohsin/mobile/platforms/update/:id
    redirectClose: mohsin/mobile/platforms

# Update page
update:
    title: Edit Platform
    redirect: mohsin/mobile/platforms
    redirectClose: mohsin/mobile/platforms

# Preview page
preview:
    title: Preview Platform
