# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Platform

# Model Form Field configuration
form: $/tempestronics/mobile/models/platform/fields.yaml

# Model Class name
modelClass: Tempestronics\Mobile\Models\Platform

# Default redirect location
defaultRedirect: tempestronics/mobile/platforms

# Create page
create:
    title: Create Platform
    redirect: tempestronics/mobile/platforms/update/:id
    redirectClose: tempestronics/mobile/platforms

# Update page
update:
    title: Edit Platform
    redirect: tempestronics/mobile/platforms
    redirectClose: tempestronics/mobile/platforms

# Preview page
preview:
    title: Preview Platform
