# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Version

# Model Form Field configuration
form: $/mohsin/mobile/models/version/fields.yaml

# Model Class name
modelClass: Mohsin\Mobile\Models\Version

# Default redirect location
defaultRedirect: mohsin/mobile/versions

# Create page
create:
    title: Create Version
    redirect: mohsin/mobile/versions/update/:id
    redirectClose: mohsin/mobile/versions

# Update page
update:
    title: Edit Version
    redirect: mohsin/mobile/versions
    redirectClose: mohsin/mobile/versions

# Preview page
preview:
    title: Preview Version