# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Version

# Model Form Field configuration
form: $/tempestronics/mobile/models/version/fields.yaml

# Model Class name
modelClass: Tempestronics\Mobile\Models\Version

# Default redirect location
defaultRedirect: tempestronics/mobile/versions

# Create page
create:
    title: Create Version
    redirect: tempestronics/mobile/versions/update/:id
    redirectClose: tempestronics/mobile/versions

# Update page
update:
    title: Edit Version
    redirect: tempestronics/mobile/versions
    redirectClose: tempestronics/mobile/versions

# Preview page
preview:
    title: Preview Version